version: '3'

services:
   db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db_mysql
      restart: always
      tty: true
      volumes:
         - ./mysql:/var/lib/mysql
      environment:
         - MYSQL_DATABASE=db_teste
         - MYSQL_ROOT_PASSWORD=root
      networks: 
         - rndnet

networks:
   rndnet:
      driver: bridge
